import Navbar from "@/components/Navbar/Navbar";
import type { Metadata } from "next";
import Sidebar from "@/components/Sidebar/page";
import styles from "./page.module.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navbar />
      <div className={styles.container}>
        <Sidebar />
        {children}
      </div>
    </>
  );
}
