import Navbar from '@/components/Navbar/Navbar';
import type { Metadata } from 'next';
import Sidebar from '@/components/Sidebar/page';
import styles from './page.module.css';
import Drawer from '@/components/Drawer/page';
import { DrawerProvider } from '@/components/Providers';
import Overlay from '@/components/Drawer/overlay';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <DrawerProvider>
      <div className={styles.page}>
        <Drawer />
        <Overlay />
        <Navbar />
        <div className={styles.container}>
          <Sidebar />
          {children}
        </div>
      </div>
    </DrawerProvider>
  );
}
